<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AudioBridge.Core\AudioBridge.Core.csproj" />
    <ProjectReference Include="..\AudioBridge.Transport\AudioBridge.Transport.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- 编译前自动结束旧进程，避免文件锁定 -->
  <Target Name="KillRunningProcess" BeforeTargets="Build">
    <Exec Command="taskkill /f /im AudioBridge.Agent.Tray.exe 2>nul || exit 0" IgnoreExitCode="true" />
  </Target>

</Project>